### ISSUE TITLE
The Overdrive Midas upgrade doesn't make the normal balls disappear in v1.11.0-beta

### ISSUE THREAD

**Issue by QuackQuackBlah** [PoochyEXE/PoochyEXE.github.io#33]
With the opacity settings so that I could only see normal balls, and when the Midas upgrade is activated by overdrive, the normal balls are still there, but now they go really fast. From what I can tell, you made it so the normal balls don't interact with anything, and just made it so they had the gold ball's effect. This would be fine, because it's highly unlikely for someone to see normal balls and not gold balls. However, the problem is, is that the midas-created gold balls themselves also zoom down the screen. 

Sorry if this issue is unclear, can explain slower and in more detail whatever is unclear :-).

**Comment by PoochyEXE** [comment]
Fixed in v1.11.1. Thanks for the bug report!

In case you're curious, the bug was because I didn't clear out the normal balls list correctly after changing them to gold, so there would be two references to each Midas-created gold ball, which made the physics engine update them twice per frame, and the rendering code would draw a normal ball and then the gold ball on top.
