### ISSUE TITLE
some buttons don't respect the notation setting

### ISSUE THREAD

**Issue by Shadlock0133** [PoochyEXE/PoochyEXE.github.io#48]
![image](https://github.com/user-attachments/assets/6cfc5dfb-0f4f-4bb3-bd87-133a997b4717)

i have set notation to japanese/chinese numerals, but some of the buttons use scientific/engineering notation instead

**Comment by PoochyEXE** [comment]
Thanks for the bug report! I just pushed a hotfix to improve the notation. It still falls back to scientific notation at e72 due to running out of named numbers, and targets still fall back at e52 because otherwise 1e55 would be rendered as "1000恒河沙" which would be unreadable if squeezed into a target. But this should be better than it was before.
